### ISSUE TITLE
error 404 skf.jeannedhack.org

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [moebiuseye/skf#13]
Please repair link in README. Possibly move docs to wiki or maintain within project files.

Thanks.

**Comment by moebiuseye** [comment]
Hi, thanks for pointing this out: I was in the middle of a server migration, and didn't think anyone would take interest in this little project over the weekend. 
Happy to be proven wrong. :) The documentation is available now.

**Comment by Anachron** [comment]
I cannot open the website right now. Is there any downtime?

**Comment by moebiuseye** [comment]
Yes. I'm migrating some vms. Some websites won't be up until probably next week.
