### ISSUE TITLE
Add alternative (competitor)

### ISSUE THREAD

**Issue by pickfire** [moebiuseye/skf#9]
Hi, I have created another static site generator (bash/mksh) some time ago for my website which is inspired by the suckless philosophy, I really hope that you can add it as alternatives.

https://github.com/pickfire/sssg

It seems like you did some nice job handling there.

**Comment by moebiuseye** [comment]
Hi, The pupose of the issues is not this type of requests. Some people have made lists of static website generators. You can request to be added there. 
Thank you for your interest.
